# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Install build dependencies for SciPy
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy project files
COPY pyproject.toml .
COPY medcalc ./medcalc

# Install the package and dependencies
RUN pip install --no-cache-dir .

# Start the MCP server
CMD ["medcalc"]
